# Generated by Django 4.2.2 on 2023-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlExp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='username',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
