# Generated by Django 4.2.2 on 2023-06-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlExp', '0002_username_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='username',
            new_name='user',
        ),
    ]
